// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RK_Hotels.Data;

namespace RK_Hotels.Migrations
{
    [DbContext(typeof(RK_HotelsDatabaseContext))]
    partial class RK_HotelsDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("RK_Hotels.Models.Booking_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Customer_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("Hotel_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("Room_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("Service_DetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Customer_DetailId");

                    b.HasIndex("Hotel_DetailId");

                    b.HasIndex("Room_DetailId");

                    b.HasIndex("Service_DetailId");

                    b.ToTable("Booking_Detail");
                });

            modelBuilder.Entity("RK_Hotels.Models.Customer_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer_Detail");
                });

            modelBuilder.Entity("RK_Hotels.Models.Hotel_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotel_Detail");
                });

            modelBuilder.Entity("RK_Hotels.Models.Room_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Price_Per_Night")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Room_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Room_Detail");
                });

            modelBuilder.Entity("RK_Hotels.Models.Service_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Availablity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opening_Hours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Service_Detail");
                });

            modelBuilder.Entity("RK_Hotels.Models.Booking_Detail", b =>
                {
                    b.HasOne("RK_Hotels.Models.Customer_Detail", "Customer_Detail")
                        .WithMany()
                        .HasForeignKey("Customer_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RK_Hotels.Models.Hotel_Detail", "Hotel_Detail")
                        .WithMany()
                        .HasForeignKey("Hotel_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RK_Hotels.Models.Room_Detail", "Room_Detail")
                        .WithMany()
                        .HasForeignKey("Room_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RK_Hotels.Models.Service_Detail", "Service_Detail")
                        .WithMany()
                        .HasForeignKey("Service_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer_Detail");

                    b.Navigation("Hotel_Detail");

                    b.Navigation("Room_Detail");

                    b.Navigation("Service_Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
